name = "GoonTime"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c25f23578b2b46d35d61eefbb45bec86007d3a6c977caba1e7381b9bad9d130"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
