name = "GoonTime"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11b6247f5fcc4f0a72f2560b7fc27d23e4425fecba53b518b32756b798fe2568"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
