name = "GoonTime"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dffe7ad54c39db233fba0ed5af8b3aafb52abc326aae60d56274fed51e545c2"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
