name = "GoonTime"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c10d7fb66c5826ea640a3a39dedcce1e972fcf14f8576c7c5fda3e3e656ad3a"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
