name = "GoonTime"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec7a01a856ba7d18c174dc29e08cf46dbdf9bd6b4119f9acf75093d86e3a790e"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
