name = "GoonTime"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d3697de51b1bfdcc395d029747eb46a456f578b588daeab3f9b9ee3bc388d63"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
