name = "GoonTime"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f91f6acaf4c329ef2f3a933bcbc2828ffce4df23626f7a2fbf1152ffa288be94"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
