# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				panda = true
				axolotl = true
				bee = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				bat = true
				husk = true
				frog = true
				hoglin = true
				experience_bottle = true
				camel = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wandering_trader = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				phantom = true
				minecart = true
				ender_dragon = true
				leash_knot = true
				glow_squid = true
				warden = true
				glow_item_frame = false
				squid = true
				shulker_bullet = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				chest_minecart = true
				fox = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				piglin = true
				cat = true
				zombie = true
				ender_pearl = true
				guardian = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				wither_skull = true
				wolf = true
				villager = true
				skeleton_horse = true
				zombie_villager = true
				elder_guardian = true
				boat = true
				polar_bear = true
				strider = true
				painting = true
				cod = true
				witch = true
				spider = true
				wither = true

			[light_sources.settings.entities.tconstruct]
				flint_shuriken = true
				ender_slime = true
				earth_slime = true
				fancy_item_frame = true
				sky_slime = true

			[light_sources.settings.entities.handcrafted]
				seat = true
				fancy_painting = true

			[light_sources.settings.entities.mca]
				grim_reaper = true
				male_zombie_villager = true
				crib = true
				female_zombie_villager = true
				female_villager = true
				male_villager = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				sludge = true
				sculk_centipede = true
				angler_fish = true
				sculk_snapper = true

			[light_sources.settings.entities.mcwfurnitures]
				chair_entity = true

			[light_sources.settings.entities.refurbished_furniture]
				seat = true

			[light_sources.settings.entities.items_displayed]
				jewelry_pillow = true
				item_display = true

			[light_sources.settings.entities.majruszsdifficulty]
				illusioner = true
				cursed_armor = true
				tank = true

			[light_sources.settings.entities.smallships]
				galley = true
				brigg = true
				drakkar = true
				cog = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.travelersbackpack]
				backpack = true

			[light_sources.settings.entities.sit]
				entity_sit = true

